files: ^module/
exclude: ^module/data/
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982' 
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-requests==2.28.11.1, types-python-dateutil==2.8.19, types_pytz==2022.4.0.0]

-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: sh -c 'isort --profile black --filter-files "$@"; git add -u' --
        language: python
        require_serial: true
        types_or:
          - python
          - pyi
        additional_dependencies:
          - isort~=5.10.1

      - id: black
        name: black
        entry: sh -c 'black "$@"; git add -u' --
        language: python
        require_serial: true
        types_or:
          - python
          - pyi
        additional_dependencies:
          - black~=22.8.0

